Issue #2: Count parameters per function
dspinellis/cqmetrics pull request #6
Opened 2017-03-19 17:01 UTC by theosotr

This pull request also changes the heuristic of function detection. Specifically:

An identifier which is followed by '(' is considered a function. This is
can be function declaration (e.g. prototype):

```c
int foo(int x);
```

or a function definition (with implementation):
```c
int foo(int x)
{
    // Code here ...
}
```

This commit handles both cases and it introduces two metrics:
- Number of functions declarations (prototypes).
- Number of function definitions.

2017-03-19 17:53 UTC, dspinellis requested changes
Nice work! Please see some minor issues.

2017-03-19 17:53 UTC, dspinellis commented on src/CMetricsCalculator.cpp
> +			 * between brackets, then functions it takes one
... the assume that the function has one parameter.

2017-03-19 17:53 UTC, dspinellis commented on src/FunctionSignature.h
> +#endif /* FUNCTIONSIGNATURE_H */
Nice!

2017-03-19 17:53 UTC, dspinellis commented on metrics.md
> +* Number of function definitons (A function with an implementation).
s/implementation/body/

2017-03-19 17:53 UTC, dspinellis commented on src/CMetricsCalculator.cpp
> +CMetricsCalculator::get_first_non_space_char(char terminated_c)
`char_before` moves you back right?  So doesn't this function return the first **previous** non-space character?

2017-03-20 10:40 UTC, theosotr commented
Done!

2019-01-10 08:39 UTC, closed without merging